BookStore/Models/Domain/Genre.cs
using System.ComponentModel.DataAnnotations;

namespace BookStore.Models.Domain;

public class Genre{

    [Key]
    public int Id { get; set; }

    [Required]
    public required string Name { get; set; }
}

BookStore/Controllers/GenreController.cs
using BookStore.Models.Domain;
using BookStore.UnitOfWork.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers;

public class GenreController : Controller
{
    private readonly IMainUnit _MainUnit;
    public GenreController(IMainUnit unit)
    {
        _MainUnit = unit;
    }

    [HttpGet]
    public async Task<IActionResult> GetAll()
    {
        var Genres = await _MainUnit.Genres.GetAllAsync();
        return View(Genres);
    }

    [HttpGet]
    public IActionResult Add()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Add(Genre model)
    {
        if(!ModelState.IsValid)
        {
            return View(model);
        }
        bool result = await _MainUnit.Genres.AddAsync(model);
        if(result)
        {
            TempData["Message"] = "Seccessful Process";
            return RedirectToAction(nameof(GetAll));
        }
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Update(int Id)
    {
        var model = await _MainUnit.Genres.GetByIdAsync(Id);
        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Update(Genre model)
    {
        if(!ModelState.IsValid)
        {
            return View(model);
        }
        bool result = await _MainUnit.Genres.UpdateAsync(model);
        if(result)
        {
            TempData["Message"] = "Seccessful Process";
            return RedirectToAction(nameof(GetAll));
        }
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Delete(int Id)
    {
        await _MainUnit.Genres.DeleteAsync(Id);
        return RedirectToAction("GetAll");
    }
}

BookStore/Views/Genre/Add.cshtml
@model BookStore.Models.Domain.Genre
@{
}

<div class="container pt-5">
    <div class="row">
        <div class="col-md-6">
            <h3>Add Genre</h3>
            <form asp-action="Add" method="post">
                <div class="form-group">
                    <label asp-for="Name">Name *</label>
                    <input type="text" class="form-control" asp-for="Name" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                @if (TempData["msg"] != null)
                {
                    <div class="form-group">
                        @TempData["msg"]
                    </div>
                }
                <div class="form-group pt-3">
                    <button type="submit" class="btn btn-dark"><i class="bi bi-save"></i> Save</button>
                    <a href="/Genre/GetAll" class="btn btn-primary"> <i class="bi bi-list"></i>List</a>
                </div>

            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

BookStore/Views/Genre/GetAll.cshtml
@model IEnumerable<BookStore.Models.Domain.Genre>
@{
}

<div class="container pt-5">
    <div class="row">
        <div class="col-md-6">
            <a class="btn btn-dark" href="/Genre/Add">Add more</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <h3>Genres</h3>

            <table  class="table table-stripped table-bordered table-dark">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var item in Model){
                    <tr>
                        <td>@item.Name</td>
                        <td>
                                <a class="btn btn-success" href="/Genre/Update?id=@item.Id" style="margin-right: 10px;"><i class="bi bi-pen"></i> Edit</a>
                                <a class="btn btn-danger" href="@Url.Action("Delete", "Genre", new { id = item.Id })">
                                    <i class="bi bi-trash"></i> Delete
                                </a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

BookStore/Views/Genre/Update.cshtml
@model BookStore.Models.Domain.Genre
@{
}

<div class="container pt-5">
    <div class="row">
        <div class="col-md-6">
            <h3>Update Genre</h3>
            <form asp-action="Update" method="post">
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Name">Name *</label>
                    <input type="text" class="form-control" asp-for="Name" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                @if (TempData["msg"] != null)
                {
                    <div class="form-group">
                        @TempData["msg"]
                    </div>
                }
                <div class="form-group pt-3">
                    <button type="submit" class="btn btn-dark"><i class="bi bi-save"></i> Save</button>
                    <a href="/Genre/GetAll" class="btn btn-primary"> <i class="bi bi-list"></i>List</a>
                </div>

            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}